### ISSUE TITLE
compiling with node v11

### ISSUE THREAD

**Issue by wanderer** [phusion/node-sha3#8]
it doesn't compile with node 0.11.13

```
> sha3@1.0.0 install /home/null/code/node-sha3
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/null/code/node-sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
../src/addon.cpp:22:35: error: expected class-name before ‘{’ token
 class SHA3Hash: public ObjectWrap {
                                   ^
../src/addon.cpp:41:12: error: ‘Arguments’ does not name a type
  New(const Arguments &args) {
            ^
../src/addon.cpp:61:15: error: ‘Arguments’ does not name a type
  Update(const Arguments &args) {
               ^
../src/addon.cpp:91:15: error: ‘Arguments’ does not name a type
  Digest(const Arguments &args) {
               ^
In file included from /home/null/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/addon.cpp:1:
/home/null/.node-gyp/0.11.14/deps/v8/include/v8.h: In static member function ‘static void SHA3Hash::Initialize(v8::Handle<v8::Object>)’:
/home/null/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/addon.cpp:29:15: error: within this context
   HandleScope scope;
               ^
../src/addon.cpp:30:56: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
   Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                        ^
../src/addon.cpp:30:56: note: candidate is:
In file included from /home/null/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/addon.cpp:1:
/home/null/.node-gyp/0.11.14/deps/v8/include/v8.h:3434:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Handle<v8::Value>, v8::Handle<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/null/.node-gyp/0.11.14/deps/v8/include/v8.h:3434:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&)’ to ‘v8::Isolate*’
../src/addon.cpp:32:19: error: ‘NewSymbol’ is not a member of ‘v8::String’
   t->SetClassName(String::NewSymbol("SHA3Hash"));
                   ^
../src/addon.cpp:34:48: error: invalid conversion from ‘v8::Handle<v8::Value> (*)(const int&)’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
   NODE_SET_PROTOTYPE_METHOD(t, "update", Update);
                                                ^
In file included from ../src/addon.cpp:1:0:
/home/null/.node-gyp/0.11.14/src/node.h:227:13: note: initializing argument 3 of ‘void node::NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate>, const char*, v8::FunctionCallback)’
 inline void NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate> recv,
             ^
../src/addon.cpp:35:48: error: invalid conversion from ‘v8::Handle<v8::Value> (*)(const int&)’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
   NODE_SET_PROTOTYPE_METHOD(t, "digest", Digest);
                                                ^
In file included from ../src/addon.cpp:1:0:
/home/null/.node-gyp/0.11.14/src/node.h:227:13: note: initializing argument 3 of ‘void node::NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate>, const char*, v8::FunctionCallback)’
 inline void NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate> recv,
             ^
../src/addon.cpp:37:15: error: ‘NewSymbol’ is not a member of ‘v8::String’
   target->Set(String::NewSymbol("SHA3Hash"), t->GetFunction());
               ^
In file included from /home/null/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/addon.cpp:1:
/home/null/.node-gyp/0.11.14/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> SHA3Hash::New(const int&)’:
/home/null/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/addon.cpp:42:15: error: within this context
   HandleScope scope;
               ^
../src/addon.cpp:46:19: error: invalid types ‘const int[int]’ for array subscript
   hashlen = args[0]->IsUndefined() ? 512 : args[0]->Int32Value();
                   ^
../src/addon.cpp:46:50: error: invalid types ‘const int[int]’ for array subscript
   hashlen = args[0]->IsUndefined() ? 512 : args[0]->Int32Value();
                                                  ^
../src/addon.cpp:48:50: error: ‘New’ is not a member of ‘v8::String’
    Local<Value> exception = Exception::TypeError(String::New("Unsupported hash length"));
                                                  ^
../src/addon.cpp:49:35: error: ‘ThrowException’ was not declared in this scope
    return ThrowException(exception);
                                   ^
../src/addon.cpp:53:8: error: ‘class SHA3Hash’ has no member named ‘Wrap’
   obj->Wrap(args.This());
        ^
../src/addon.cpp:53:18: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
   obj->Wrap(args.This());
                  ^
../src/addon.cpp:57:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(args.This());
                ^
../src/addon.cpp:57:27: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
   return scope.Close(args.This());
                           ^
In file included from /home/null/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/addon.cpp:1:
/home/null/.node-gyp/0.11.14/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> SHA3Hash::Update(const int&)’:
/home/null/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/addon.cpp:62:15: error: within this context
   HandleScope scope;
               ^
../src/addon.cpp:63:19: error: ‘ObjectWrap’ has not been declared
   SHA3Hash *obj = ObjectWrap::Unwrap<SHA3Hash>(args.This());
                   ^
../src/addon.cpp:63:46: error: expected primary-expression before ‘>’ token
   SHA3Hash *obj = ObjectWrap::Unwrap<SHA3Hash>(args.This());
                                              ^
../src/addon.cpp:63:53: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
   SHA3Hash *obj = ObjectWrap::Unwrap<SHA3Hash>(args.This());
                                                     ^
../src/addon.cpp:65:36: error: invalid types ‘const int[int]’ for array subscript
   ASSERT_IS_STRING_OR_BUFFER(args[0]);
                                    ^
../src/addon.cpp:12:7: note: in definition of macro ‘ASSERT_IS_STRING_OR_BUFFER’
  if (!val->IsString() && !Buffer::HasInstance(val)) { \
       ^
../src/addon.cpp:65:36: error: invalid types ‘const int[int]’ for array subscript
   ASSERT_IS_STRING_OR_BUFFER(args[0]);
                                    ^
../src/addon.cpp:12:47: note: in definition of macro ‘ASSERT_IS_STRING_OR_BUFFER’
  if (!val->IsString() && !Buffer::HasInstance(val)) { \
                                               ^
../src/addon.cpp:13:46: error: ‘New’ is not a member of ‘v8::String’
   return ThrowException(Exception::TypeError(String::New("Not a string or buffer"))); \
                                              ^
../src/addon.cpp:65:3: note: in expansion of macro ‘ASSERT_IS_STRING_OR_BUFFER’
   ASSERT_IS_STRING_OR_BUFFER(args[0]);
   ^
../src/addon.cpp:13:84: error: ‘ThrowException’ was not declared in this scope
   return ThrowException(Exception::TypeError(String::New("Not a string or buffer"))); \
                                                                                    ^
../src/addon.cpp:65:3: note: in expansion of macro ‘ASSERT_IS_STRING_OR_BUFFER’
   ASSERT_IS_STRING_OR_BUFFER(args[0]);
   ^
../src/addon.cpp:66:43: error: invalid types ‘const int[int]’ for array subscript
   enum encoding enc = ParseEncoding(args[1]);
                                           ^
../src/addon.cpp:67:35: error: invalid types ‘const int[int]’ for array subscript
   ssize_t len = DecodeBytes(args[0], enc);
                                   ^
../src/addon.cpp:70:46: error: ‘New’ is not a member of ‘v8::String’
    Local<Value> exception = Exception::Error(String::New("Bad argument"));
                                              ^
../src/addon.cpp:71:35: error: ‘ThrowException’ was not declared in this scope
    return ThrowException(exception);
                                   ^
../src/addon.cpp:74:33: error: invalid types ‘const int[int]’ for array subscript
   if (Buffer::HasInstance(args[0])) {
                                 ^
../src/addon.cpp:75:37: error: invalid types ‘const int[int]’ for array subscript
    Local<Object> buffer_obj = args[0]->ToObject();
                                     ^
../src/addon.cpp:81:50: error: invalid types ‘const int[int]’ for array subscript
    ssize_t written = DecodeWrite(buf, len, args[0], enc);
                                                  ^
../src/addon.cpp:87:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(args.This());
                ^
../src/addon.cpp:87:27: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
   return scope.Close(args.This());
                           ^
In file included from /home/null/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/addon.cpp:1:
/home/null/.node-gyp/0.11.14/deps/v8/include/v8.h: In static member function ‘static v8::Handle<v8::Value> SHA3Hash::Digest(const int&)’:
/home/null/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/addon.cpp:92:15: error: within this context
   HandleScope scope;
               ^
../src/addon.cpp:93:19: error: ‘ObjectWrap’ has not been declared
   SHA3Hash *obj = ObjectWrap::Unwrap<SHA3Hash>(args.This());
                   ^
../src/addon.cpp:93:46: error: expected primary-expression before ‘>’ token
   SHA3Hash *obj = ObjectWrap::Unwrap<SHA3Hash>(args.This());
                                              ^
../src/addon.cpp:93:53: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
   SHA3Hash *obj = ObjectWrap::Unwrap<SHA3Hash>(args.This());
                                                     ^
../src/addon.cpp:101:43: error: invalid types ‘const int[int]’ for array subscript
   enum encoding enc = ParseEncoding(args[0], BINARY);
                                           ^
../src/addon.cpp:110:46: error: ‘New’ is not a member of ‘v8::String’
    Local<Value> exception = Exception::Error(String::New("Unsupported output encoding"));
                                              ^
../src/addon.cpp:111:35: error: ‘ThrowException’ was not declared in this scope
    return ThrowException(exception);
                                   ^
../src/addon.cpp:114:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(outString);
                ^
../src/addon.cpp:115:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
../src/addon.cpp: In static member function ‘static v8::Handle<v8::Value> SHA3Hash::Update(const int&)’:
../src/addon.cpp:88:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
sha3.target.mk:88: recipe for target 'Release/obj.target/sha3/src/addon.o' failed
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
make: Leaving directory '/home/null/code/node-sha3/build'
```

**Comment by parkr** [comment]
Working on this today. Looks like v8 has changed a lot.

**Comment by MrNice** [comment]
@wanderer Hey I got @parkr  and @vladlosev to fix this: https://github.com/phusion/node-sha3/pull/9 

Feel free to point your package at the git commit (npm can install from github as well as from the npm registry) until this fix gets added.

**Comment by wanderer** [comment]
thank you, great work @MrNice @parkr and @vladlosev !

**Comment by MrNice** [comment]
I literally did nothing.

**Comment by parkr** [comment]
Fixed by #10
